fix(scalelite): see greenstatic/bigbluebutton-exporter#55
```
2020-09-13 07:29:34,642 [INFO]: HTTP server started on port: 9688
2020-09-13 07:29:34,643 [INFO]: Collecting metrics from BigBlueButton API
2020-09-13 07:29:34,643 [DEBUG]: Requesting via API meetings data
2020-09-13 07:29:34,643 [INFO]: TLS CA verification has been disabled for API call
2020-09-13 07:29:34,646 [DEBUG]: Starting new HTTPS connection (1): scalelite.xxx:443
2020-09-13 07:29:34,713 [DEBUG]: https://scalelite.xxx:443 "GET /bigbluebutton/api/getMeetings?checksum=yyy
HTTP/1.1" 200 None
<?xml version="1.0"?>
<response>
  <returncode>SUCCESS</returncode>
  <messageKey>noMeetings</messageKey>
  <message>No meetings were found on this server.</message>
</response>
Traceback (most recent call last):
  File "server.py", line 46, in <module>
    REGISTRY.register(collector)
  File
"/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py",
line 24, in register
    names = self._get_names(collector)
  File
"/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py",
line 64, in _get_names
    for metric in desc_func():
  File "/app/collector.py", line 55, in collect
    meetings, meetings_data_latency =
execution_duration(api.get_meetings)()
  File "/app/helpers.py", line 19, in wrapper
    result = fun(*args, **kwargs)
  File "/app/api.py", line 14, in get_meetings
    if data['response']['meetings'] is None:
KeyError: 'meetings'
```